name: unified_3d
channels:
  - conda-forge
  - pkgs/main
  - nvidia
  - pytorch
dependencies:
  - certifi
  - charset-normalizer
  - cmake
  - cython
  - idna
  - matplotlib
  - opencv
  - pandas
  - python=3.11
  - pytorch
  - pytorch-cuda=12.1
  - requests
  - scikit-image
  - scipy=1.13
  - seaborn
  - torchaudio
  - torchvision